### ISSUE TITLE
Ceph install 

### ISSUE THREAD

**Issue by Klesti8701** [OpenLabsHackerspace/infracenter#4]
install Ceph storage and configure to be used by proxmox VMs

**Comment by kominoshja** [comment]
Note: the CEPH cluster will have HDDs. Once we have enough donated hardware, we can improve

**Comment by kominoshja** [comment]
Ceph has been installed. Details:

* Public network: (vmbr0) 10.10.1.1/16 (can be moved to public IPs if ISP provides, allows cluster bigger than LAN)
* Private network: (vmbr9) 20.20.1.1/24  (double check needed) (uses 10Gb NICs)

PVE1 (desktop 1):
* MDS
* MON1
* MGR1
* OSD1-OSD4

PVE2 (thinkcenter):
* MON2

PVE3 (desktop 2):
* MON3
* MGR2

Fault tolerance level: OSD

**Comment by kominoshja** [comment]
Ceph has been installed. Details:

* Public network: (vmbr0) 10.10.1.1/16 (can be moved to public IPs if ISP provides, allows cluster bigger than LAN)
* Private network: (vmbr9) 20.20.1.1/24  (double check needed) (uses 10Gb NICs)

PVE1 (desktop 1):
* MDS
* MON1
* MGR1
* OSD1-OSD4

PVE2 (thinkcenter):
* MON2

PVE3 (desktop 2):
* MON3
* MGR2

Fault tolerance level: OSD
